@HotelListing.Api_HostAddress = https://localhost:7142
@json = application/json
@apiKey = dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=
###

@id=3

//Get all countries
GET {{HotelListing.Api_HostAddress}}/api/countries
X-Api-Key: {{apiKey}}
//Authorization: Basic dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=
###



//Add new country
POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: {{json}}
{
  "name": "Test Country",
  "shortname": "IC"
}
###



//Delete a specific country
DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###



//Get a specific country
GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###



//Update a specific country
PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: {{json}}

{
  "countryId": 8,
  "name": "Jamaica",
  "shortname": "JM"
}
###



//Get all hotels
GET {{HotelListing.Api_HostAddress}}/api/hotels

###



//Add a new hotel
POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: {{json}}

{
  "Name": "Test",
  "Address": "123",
  "Rating": 4.5,
  "CountryId": 8
}
###



//Delete a specific hotel
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###



//Get a specific hotel
GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###



//Update a specific hotel
PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: {{json}}

{
  "Id": 7,
  "Name": "Ocean Coral",
  "Address": "Trelawny, Jamaica",
  "Rating": 4.5,
  "CountryId": 7
}
###



//Register User
POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "user1@localhost.com",
  "password": "P@ssword1",
  "firstName": "First",
  "lastName": "Last"
}
###



//Login
POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "user2@localhost.com",
  "password": "P@ssword1"
}
###



//Register
POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "user2@localhost.com",
  "password": "P@ssword1",
  "firstName": "First",
  "lastName": "Last"
}
###
