@HotelListing.Api_HostAddress = https://localhost:7142
@json = application/json
@apiKey=dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzrbd29yZDE=
@token = inserthere
@id=3
@countryId=6
@pageSize=5

GET {{HotelListing.Api_HostAddress}}/api/countries
#Authorization: Bearer {{token}}
###

GET {{HotelListing.Api_HostAddress}}/api/countries?Search=United
Authorization: Bearer {{token}}
###

# Get Country Hotels - Large Page Size
GET {{HotelListing.Api_HostAddress}}/api/countries/{{countryId}}/hotels?pageNumber=1&pageSize=20
Authorization: Bearer {{token}}
###

POST {{HotelListing.Api_HostAddress}}/api/countries
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "name": "Test Admin Country",
  "shortName": "TAC"
}

###

DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Authorization: Bearer inserthere
###

GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
###

GET {{HotelListing.Api_HostAddress}}/api/countries/
Authorization: Bearer {{token}}

###

PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: {{json}}
{
  "countryId": 2,
  "name": "Jamaica",
  "shortName": "JM"
}
###

PATCH {{HotelListing.Api_HostAddress}}/api/countries/{{countryId}}
Authorization: Bearer {{token}}
Content-Type: application/json-patch+json

[
  {
    "op": "replace",  
    "path": "/shortName",
    "value": "TAC"
  }
]
###

GET {{HotelListing.Api_HostAddress}}/api/hotels
Authorization: Bearer inserthere
###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: {{json}}
Authorization: Bearer inserthere
{
  "Name": "Jewels Runaway Bay",
  "Address": "Ocho Rios, Jamaica",
  "Rating": 5,
  "CountryId": 3
}

###
@id=3
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Authorization: Bearer {{token}}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: {{json}}
{
  "Id": 3,
  "Name": "Ocean Coral",
  "Address": "Trelawny, Jamaica",
  "Rating": 4.5,
  "CountryId": 100
}

###
POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}
{
  "email": "user1@localhost.com",
  "password": "P@ssword1",
  "firstName":"First",
  "lastName": "Last"
}

###
POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin1@localhost.com",
  "password": "P@ssword1"
}

###
POST {{HotelListing.Api_HostAddress}}/api/defaultauth/login
Content-Type: application/json

{
  "email": "user@localhost.com",
  "password": "P@ssword1"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "admin1@localhost.com",
  "password": "P@ssword1",
  "firstName":"First",
  "lastName": "Last",
  "role": "Administrator"
}

###

GET {{HotelListing.Api_HostAddress}}/api/apikey
X-Api-Key: {{apiKey}}

###

GET {{HotelListing.Api_HostAddress}}/api/basicauth
Authorization: Basic dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=

###


PUT {{HotelListing.Api_HostAddress}}/api/hotels/1/bookings/1/admin/cancel
Authorization: Bearer inserthere
###